export const config: {
  ETH_POS_CONTRACT_ADDRESS: string
  ETH_POW_CONTRACT_ADDRESS: string
  SUBGRAPH_POW_URL: string
  SUBGRAPH_POS_URL: string
  INFURA_KEY: string
  NETWORK: string
} = {
  ETH_POS_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_ETH_POS_CONTRACT_ADDRESS || '',
  ETH_POW_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_ETH_POW_CONTRACT_ADDRESS || '',
  SUBGRAPH_POW_URL: process.env.NEXT_PUBLIC_SUBGRAPH_POW_URL || '',
  SUBGRAPH_POS_URL: process.env.NEXT_PUBLIC_SUBGRAPH_POS_URL || '',
  INFURA_KEY: process.env.NEXT_PUBLIC_INFURA_KEY || '',
  NETWORK: process.env.NEXT_PUBLIC_NETWORK || '',
}

export const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'

export default config
